@startuml pkv_ersatzverfahren

hide footbox
title Bereitstellung KVNR über VSD Ersatzbescheinigung
actor Vers as "Versicherte" #ee8360
participant App as "PKV App" #009a7c
actor LE as "Praxis" #ee8360
participant PVS as "Primärsystem" #ee8360
participant KIMCM1 as "KIM-Clientmodul" #8da5c4
participant KIMFD as "KIM-Fachdienste" #8da5c4
participant KIMCM2 as "KIM-Clientmodul" #8da5c4
participant Kasse as "Krankenkasse (PKV)" #009a7c

Vers -> App: Praxis Check-In
activate App #009a7c
App -> App: QR-Code\nscannen
App -> App: Praxis-KIM-Adresse extrahieren
App -> Kasse: Check-In bei Praxis ( KIM-Adresse )
activate Kasse #00907c
App --> Vers:
deactivate App
Kasse -> Kasse: (1)
Kasse -> KIMCM2: (2)
deactivate Kasse
activate KIMCM2 #8da5c4
KIMCM2 -> KIMFD: (3)
deactivate KIMCM2
activate KIMFD #8da5c4
KIMFD -> KIMCM1: (4)
deactivate KIMFD
activate KIMCM1 #8da5c4
KIMCM1 -> PVS: (5)
deactivate KIMCM1
activate PVS #ee8360
PVS -> PVS: (6)
PVS ---> LE: :Hinweis Check-In\n(neuer) Patient
deactivate PVS

@enduml